name: "daily allerts"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "10 20 * * 1,2,3,4,5,6"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 25
    env:
      USERNAME: ${{ secrets.GH_USER }}
      TOKEN: ${{ secrets.GH_TOKEN }}
      OPENAI_API_KEYS: ${{ secrets.OPENAI_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_KEY }}
      DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_URL }}
      LANGUAGE: "zh"
    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python 3.9
          uses: actions/setup-python@v1
          with:
            python-version: 3.9

      -   name: Setup dependencies
          run: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install python-dotenv
      -   name: Run backup
          run: python main.py

      -   name: Commit changes
          uses: elstudio/actions-js-build/commit@v3
          with:
            commitMessage: Automated snapshot
